version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/wallet-app-deploy/
hooks:
  BeforeInstall:
    - location: generate-configs.sh
  ApplicationStart:
    - location: start-containers.sh
  ValidateService:
    - location: start-projection-runner.sh