FROM node:19.8.1

ENV NODE_OPTIONS=--openssl-legacy-provider

COPY wallet-views/typescript-client /wallet-views/typescript-client

WORKDIR /wallet-ui

COPY wallet-ui/package.json .

RUN npm install

COPY wallet-ui .

RUN npm install -g serve

EXPOSE 8090

CMD ["sh", "-c", "npm run build && serve -s build -l 8090"]

