FROM adoptopenjdk/openjdk11:alpine

WORKDIR /app

ARG VERSION

ARG JAR_FILE=/wallet-views/java/target/wallet-views-${VERSION}.jar

COPY ${JAR_FILE} wallet-views.jar

VOLUME /app/config

ENTRYPOINT ["java", "-jar", "/app/wallet-views.jar", "--spring.config.name=application", "--spring.config.location=file:/app/config/"]